# Configuraci칩n optimizada para Next.js con exportaci칩n est치tica
ignoredBuiltDependencies:
  - sharp  # Ignoramos sharp ya que usamos im치genes no optimizadas
onlyBuiltDependencies:
  - esbuild  # Solo construimos esbuild que es esencial para Next.js
