export const cartStyles = {
  container: {
    bg: "white",
    p: 5,
    borderRadius: "lg",
    boxShadow: "lg",
    mb: 5,
    border: "1px solid",
    borderColor: "gray.100",
    transition: "all 0.3s ease",
    _hover: {
      boxShadow: "xl",
      borderColor: "blue.100",
    },
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mb: 4,
    pb: 3,
    borderBottom: "2px solid",
    borderColor: "blue.100",
  },
  title: {
    fontSize: "xl",
    fontWeight: "bold",
    color: "blue.700",
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  itemContainer: {
    py: 2,
    borderBottom: "1px solid",
    borderColor: "gray.100",
    transition: "all 0.2s",
    _hover: {
      bg: "blue.50",
      borderRadius: "md",
      px: 2,
      mx: -2,
    },
  },
  itemTitle: {
    fontWeight: "medium",
    fontSize: "md",
    color: "gray.700",
    maxW: { base: "150px", md: "250px" },
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  quantityControl: {
    display: "flex",
    alignItems: "center",
    bg: "gray.50",
    borderRadius: "md",
    p: 1,
    border: "1px solid",
    borderColor: "gray.200",
  },
  quantityButton: {
    minW: "24px",
    h: "24px",
    p: 0,
    borderRadius: "md",
    fontSize: "xs",
  },
  quantityText: {
    mx: 2,
    fontWeight: "bold",
    fontSize: "sm",
    color: "gray.700",
    minW: "20px",
    textAlign: "center",
  },
  priceText: {
    fontWeight: "bold",
    color: "blue.600",
    fontSize: "sm",
    ml: 3,
  },
  removeButton: {
    minW: "24px",
    h: "24px",
    p: 0,
    borderRadius: "full",
    ml: 2,
  },
  totalContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    mt: 4,
    pt: 3,
    borderTop: "2px solid",
    borderColor: "blue.100",
    fontWeight: "bold",
  },
  totalLabel: {
    fontSize: "lg",
    color: "gray.700",
  },
  totalAmount: {
    fontSize: "xl",
    color: "blue.700",
  },
  emptyCart: {
    textAlign: "center",
    py: 8,
    color: "gray.500",
  },
  checkoutButton: {
    colorScheme: "whatsapp",
    size: "lg",
    fontWeight: "bold",
    borderRadius: "full",
    boxShadow: "0 4px 12px rgba(37, 211, 102, 0.5)",
    px: 8,
    py: 6,
    w: { base: "100%", md: "auto" },
    _hover: { 
      transform: "translateY(-3px)",
      boxShadow: "0 6px 16px rgba(37, 211, 102, 0.6)",
    },
    _active: {
      transform: "translateY(1px)",
      boxShadow: "0 2px 8px rgba(37, 211, 102, 0.4)",
    },
    transition: "all 0.3s ease",
  },
  checkoutContainer: {
    position: "sticky",
    bottom: 0,
    justifyContent: "center",
    padding: 4,
    backdropFilter: "blur(8px)",
    bg: "rgba(255, 255, 255, 0.8)",
    zIndex: 10,
    borderTop: "1px solid",
    borderColor: "gray.100",
  },
  animation: {
    fadeIn: {
      from: { opacity: 0, transform: "translateY(10px)" },
      to: { opacity: 1, transform: "translateY(0)" }
    }
  }
};